name: Bug Report
description: Template to report a bug.
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also describe the exact problem you are experiencing, and if possible, provide a step-by-step guide to reproduce the issue.
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: Which version of the project is affected?
      placeholder: ex. v1.0.0
    validations:
      required: true
  - type: input
    id: operating-system
    attributes:
      label: Operating System
      description: Which operating system is affected?
      placeholder: ex. Sonoma 14.5
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/zumodeus/clip/blob/master/CODE_OF_CONDUCT.md). 
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
