name: New Feature
description: Template to request a new feature.
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: what-is-your-proposal
    attributes:
      label: What is your proposal?
      description: Outline the purpose of the feature, its benefits, and any specific requirements or functionality you envision.
      placeholder: Describe the feature and its benefits to the project and its users!
    validations:
      required: true
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: true
  - type: dropdown
    id: type
    attributes:
      label: Which type of change will this be?
      description: Remember, MAJOR involves a complete change or the addition of new functionality, while MINOR involves an improvement to existing functionality.
      multiple: false
      options:
        - MAJOR
        - MINOR
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/zumodeus/clip/blob/master/CODE_OF_CONDUCT.md). 
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
